# Generated by Django 3.0.7 on 2020-08-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomusermodel',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='mycustomusermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
