# Generated by Django 3.1 on 2020-09-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_imgs/default.png', null=True, upload_to='profile_imgs/'),
        ),
    ]
