# Generated by Django 3.0.7 on 2020-08-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0002_auto_20200809_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomusermodel',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='mycustomusermodel',
            name='user_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imgs/'),
        ),
    ]
