# Generated by Django 3.0.7 on 2020-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0003_auto_20200810_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mycustomusermodel',
            name='user_address',
        ),
    ]
