# Generated by Django 3.0.7 on 2020-08-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0004_auto_20200810_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='ana_account.MyCustomUserModel'),
        ),
    ]
