# Generated by Django 3.0.7 on 2020-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0007_auto_20200811_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='melli_code',
            field=models.BigIntegerField(default=None, max_length=10),
        ),
    ]
