# Generated by Django 3.0.7 on 2020-08-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0008_auto_20200811_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='melli_code',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
