# Generated by Django 3.0.7 on 2020-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0012_auto_20200811_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='melli_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
