# Generated by Django 3.0.7 on 2020-08-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0014_auto_20200811_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='melli_code',
            field=models.IntegerField(blank=True, null=True, verbose_name=range(1111111111, 9999999999)),
        ),
    ]
