# Generated by Django 3.0.7 on 2020-08-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0024_auto_20200811_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomusermodel',
            name='melli_code',
        ),
        migrations.RemoveField(
            model_name='mycustomusermodel',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='mycustomusermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_imgs/default.png', upload_to='profile_imgs/'),
        ),
    ]
