# Generated by Django 3.0.7 on 2020-08-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0027_mycustomusermodel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomusermodel',
            name='melli_code',
        ),
        migrations.RemoveField(
            model_name='mycustomusermodel',
            name='phone_number',
        ),
    ]
