# Generated by Django 3.1 on 2020-08-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0033_customtokenmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTokenModel',
        ),
    ]
