# Generated by Django 3.1 on 2020-08-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ana_account', '0036_delete_customtokenmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycustomusermodel',
            options={'verbose_name': 'CustomUser', 'verbose_name_plural': 'CustomUsers'},
        ),
    ]
