# Generated by Django 3.1 on 2020-08-26 01:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ana_products', '0018_auto_20200811_0327'),
        ('ana_cart', '0002_auto_20200825_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
