# Generated by Django 3.1 on 2020-08-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_cart', '0007_auto_20200830_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
