# Generated by Django 3.1 on 2020-08-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_cart', '0008_auto_20200831_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
