# Generated by Django 3.0.7 on 2020-06-24 10:09

import ana_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField(default=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ana_products.models.upload_image_path)),
            ],
        ),
    ]
