# Generated by Django 3.0.7 on 2020-06-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_products', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='mini_image',
            field=models.ImageField(blank=True, upload_to='products_img/'),
        ),
    ]
