# Generated by Django 3.0.7 on 2020-06-29 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ana_products', '0004_auto_20200628_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ana_products.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('موجود', 'موجود'), ('ناموجود', 'ناموجود')], default='M', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ana_products.SubCategory'),
        ),
    ]
