# Generated by Django 3.0.7 on 2020-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_products', '0007_auto_20200629_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='abc'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, default='abc'),
        ),
    ]
