# Generated by Django 3.0.7 on 2020-07-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_products', '0011_auto_20200710_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
