# Generated by Django 3.0.7 on 2020-07-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ana_products', '0015_auto_20200718_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
