# Generated by Django 3.1 on 2020-09-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IranOstan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amar_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'iran_ostan',
            },
        ),
        migrations.CreateModel(
            name='IranShahr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shahr_type', models.IntegerField(blank=True, null=True)),
                ('shahrestan', models.IntegerField(blank=True, null=True)),
                ('bakhsh', models.IntegerField(blank=True, null=True)),
                ('amar_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ostan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iran_db.iranostan')),
            ],
            options={
                'db_table': 'iran_shahr',
            },
        ),
    ]
