# Generated by Django 3.1 on 2020-09-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iran_db', '0002_auto_20200904_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iranshahr',
            name='ostan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iran_db.iranostan'),
        ),
    ]
